services:
  backend:
    image: ghcr.io/christianharris-3/flashcards-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
#    env_file:
#      - ./backend/.env
    expose:
      - "8080"
    restart: unless-stopped

  frontend:
    image: ghcr.io/christianharris-3/flashcards-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    expose:
      - "80"
    restart: unless-stopped

  caddy:
    image: caddy:2-alpine
    depends_on:
      - frontend
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - caddy
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config: